package com.woniu.mapper;

import com.woniu.entity.Permiss;
import com.woniu.entity.PermissExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    long countByExample(PermissExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByExample(PermissExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insert(Permiss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insertSelective(Permiss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    List<Permiss> selectByExample(PermissExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    Permiss selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") Permiss record, @Param("example") PermissExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExample(@Param("record") Permiss record, @Param("example") PermissExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByPrimaryKeySelective(Permiss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permiss
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByPrimaryKey(Permiss record);
}