package com.woniu.mapper;

import com.woniu.entity.MyRoleExample;
import com.woniu.entity.Role;
import com.woniu.entity.RoleExample;
import com.woniu.entity.User;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	long countByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int deleteByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int deleteByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	List<Role> selectByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	Role selectByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByPrimaryKey(Role record);

	List<User> selectByOrCondition(MyRoleExample myRoleExample);
}