package com.woniu.mapper;

import com.woniu.entity.RolepExample;
import com.woniu.entity.RolepKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    long countByExample(RolepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByExample(RolepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByPrimaryKey(RolepKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insert(RolepKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insertSelective(RolepKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    List<RolepKey> selectByExample(RolepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolepKey record, @Param("example") RolepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolep
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExample(@Param("record") RolepKey record, @Param("example") RolepExample example);
}