package com.woniu.mapper;

import com.woniu.entity.Rolepermission;
import com.woniu.entity.RolepermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolepermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    long countByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int deleteByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int deleteByPrimaryKey(Integer rpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int insert(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int insertSelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    List<Rolepermission> selectByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    Rolepermission selectByPrimaryKey(Integer rpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Rolepermission record, @Param("example") RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int updateByExample(@Param("record") Rolepermission record, @Param("example") RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int updateByPrimaryKeySelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    int updateByPrimaryKey(Rolepermission record);
}