package com.woniu.mapper;

import com.woniu.entity.Userrole;
import com.woniu.entity.UserroleExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserroleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	long countByExample(UserroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int deleteByExample(UserroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int deleteByPrimaryKey(Integer urid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int insert(Userrole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int insertSelective(Userrole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	List<Userrole> selectByExample(UserroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	Userrole selectByPrimaryKey(Integer urid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByExampleSelective(@Param("record") Userrole record, @Param("example") UserroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByExample(@Param("record") Userrole record, @Param("example") UserroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByPrimaryKeySelective(Userrole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table userrole
	 *
	 * @mbg.generated Wed Jun 10 10:55:44 CST 2020
	 */
	int updateByPrimaryKey(Userrole record);

	void insertAll(Map<String, Object> map);
}