package com.woniu.mapper;

import com.woniu.entity.UserroleExample;
import com.woniu.entity.UserroleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    long countByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int deleteByPrimaryKey(UserroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insert(UserroleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int insertSelective(UserroleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    List<UserroleKey> selectByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserroleKey record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    int updateByExample(@Param("record") UserroleKey record, @Param("example") UserroleExample example);
}