package com.woniu.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.pid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.pname
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.parentid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.url
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.pid
     *
     * @return the value of permission.pid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.pid
     *
     * @param pid the value for permission.pid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.pname
     *
     * @return the value of permission.pname
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.pname
     *
     * @param pname the value for permission.pname
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.parentid
     *
     * @return the value of permission.parentid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.parentid
     *
     * @param parentid the value for permission.parentid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.url
     *
     * @return the value of permission.url
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.url
     *
     * @param url the value for permission.url
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}