package com.woniu.entity;

public class Permiss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permiss.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permiss.pname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permiss.pid
     *
     * @return the value of permiss.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permiss.pid
     *
     * @param pid the value for permiss.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permiss.pname
     *
     * @return the value of permiss.pname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permiss.pname
     *
     * @param pname the value for permiss.pname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}