package com.woniu.entity;

public class RolepKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolep.rid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolep.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolep.rid
     *
     * @return the value of rolep.rid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolep.rid
     *
     * @param rid the value for rolep.rid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolep.pid
     *
     * @return the value of rolep.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolep.pid
     *
     * @param pid the value for rolep.pid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}