package com.woniu.entity;

public class Rolepermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.rpid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    private Integer rpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.rid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.pid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.rpid
     *
     * @return the value of rolepermission.rpid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.rpid
     *
     * @param rpid the value for rolepermission.rpid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.rid
     *
     * @return the value of rolepermission.rid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.rid
     *
     * @param rid the value for rolepermission.rid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.pid
     *
     * @return the value of rolepermission.pid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.pid
     *
     * @param pid the value for rolepermission.pid
     *
     * @mbg.generated Tue Jun 09 10:55:36 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}