package com.woniu.entity;

public class Userrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.urid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private Integer urid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.uid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.rid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.urid
     *
     * @return the value of userrole.urid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.urid
     *
     * @param urid the value for userrole.urid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.uid
     *
     * @return the value of userrole.uid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.uid
     *
     * @param uid the value for userrole.uid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.rid
     *
     * @return the value of userrole.rid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.rid
     *
     * @param rid the value for userrole.rid
     *
     * @mbg.generated Wed Jun 10 10:55:44 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}