package com.woniu.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role..user.uid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role..user.uaccount
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private String uaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role..user.uname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role..user.upwd
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role..user.umail
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    private String umail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role..user.uid
     *
     * @return the value of rbac_role..user.uid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role..user.uid
     *
     * @param uid the value for rbac_role..user.uid
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role..user.uaccount
     *
     * @return the value of rbac_role..user.uaccount
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public String getUaccount() {
        return uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role..user.uaccount
     *
     * @param uaccount the value for rbac_role..user.uaccount
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setUaccount(String uaccount) {
        this.uaccount = uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role..user.uname
     *
     * @return the value of rbac_role..user.uname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role..user.uname
     *
     * @param uname the value for rbac_role..user.uname
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role..user.upwd
     *
     * @return the value of rbac_role..user.upwd
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role..user.upwd
     *
     * @param upwd the value for rbac_role..user.upwd
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role..user.umail
     *
     * @return the value of rbac_role..user.umail
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public String getUmail() {
        return umail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role..user.umail
     *
     * @param umail the value for rbac_role..user.umail
     *
     * @mbg.generated Mon Jun 08 18:41:40 CST 2020
     */
    public void setUmail(String umail) {
        this.umail = umail;
    }
}